import os, shutil, socket, subprocess, tempfile, time
from pathlib import Path
from urllib.request import urlopen
from playwright.sync_api import sync_playwright, expect
root=Path(__file__).resolve().parent.parent
with tempfile.TemporaryDirectory() as data:
    with socket.socket() as sock:
        sock.bind(('127.0.0.1',0));port=sock.getsockname()[1]
    origin=f'http://127.0.0.1:{port}'
    env={**os.environ,'CARD_APP_DATA_DIR':data,'CARD_APP_TEACHER_PIN':'123456','CARD_APP_PORT':str(port)}
    with open(Path(data)/'server.log','w+') as log:
        server=subprocess.Popen([str(root/'.venv/bin/python'),'run.py'],cwd=root,env=env,stdout=log,stderr=log)
        try:
            for _ in range(80):
                try:
                    if urlopen(origin+'/api/health',timeout=1).status==200:break
                except OSError:time.sleep(.1)
            else:raise RuntimeError('server unavailable')
            with sync_playwright() as p:
                browser=p.chromium.launch(executable_path=os.environ.get('CARD_APP_TEST_BROWSER') or shutil.which('google-chrome') or shutil.which('chromium'),headless=True)
                page=browser.new_page(viewport={'width':1280,'height':900})
                errors=[];external=[];page.on('pageerror',lambda err:errors.append(str(err)))
                def local_only(route):
                    if route.request.url.startswith(origin+'/'):route.continue_()
                    else:external.append(route.request.url);route.abort()
                page.route('**/*',local_only)
                page.goto(origin+'/teacher')
                page.get_by_label('Teacher PIN').fill('123456')
                page.get_by_role('button',name='Open teacher space').click()
                expect(page.get_by_role('heading',name='Projects',exact=True)).to_be_visible()
                page.get_by_role('button',name='Open project').first.click()
                expect(page.locator('#student-qr')).to_be_visible()
                expect(page.locator('#tab-overview')).to_be_visible()
                expect(page.locator('#cards-heading')).to_be_visible()
                expect(page.locator('#import-identity')).to_have_count(0)
                page.locator('[data-tab=layout]').click()
                expect(page.locator('#layout-art svg')).to_be_visible(timeout=15000)
                expect(page.locator('#download-svg')).to_have_attribute('href',__import__('re').compile(r'design.svg'))
                expect(page.locator("#allowed-themes input")).to_have_count(7)
                expect(page.locator("#field-settings details")).not_to_have_count(0)
                page.locator("#allowed-themes input[value=light-gray]").uncheck()
                with page.expect_navigation():
                    page.get_by_role("button",name="Save fields & themes").click()
                expect(page.locator("#cards-heading")).to_be_visible()
                page.locator("[data-tab=layout]").click()
                expect(page.locator("#allowed-themes input[value=light-gray]")).not_to_be_checked()
                page.locator('[data-tab=print]').click()
                expect(page.locator('#tab-print')).to_be_visible()
                page.locator('[data-tab=overview]').click()
                expect(page.locator('#project-title')).to_have_value('Classroom field guide')
                page.goto(origin+'/teacher')
                page.locator('#new-project-title').fill('SVG browser test')
                page.get_by_role('button',name='Create project').click()
                expect(page.locator('#project-heading')).to_have_text('SVG browser test')
                page.locator('[data-tab=layout]').click()
                expect(page.locator('#download-svg')).to_be_visible()
                expect(page.locator('#layout-preset option')).to_have_count(10)
                page.locator('#layout-preset').select_option('organism-rounded')
                page.once('dialog',lambda dialog:dialog.accept())
                page.locator('#new-layout').click()
                expect(page.locator('#studio-status')).to_contain_text('is ready')
                assert float(page.locator('#card-radius').input_value()) > 8
                expect(page.locator('.csv-import-section').first).to_be_hidden()
                expect(page.locator('.csv-import-section').last).to_be_hidden()
                assert page.evaluate("""() => {
                    const button = document.querySelector('#open-csv-import');
                    const bar = document.querySelector('.project-bar');
                    return Boolean(button.compareDocumentPosition(bar) & Node.DOCUMENT_POSITION_FOLLOWING);
                }""")
                page.locator('#open-csv-import').click()
                expect(page.locator('#open-csv-import')).to_have_attribute('aria-expanded','true')
                expect(page.locator('.csv-import-section').first).to_be_visible()
                expect(page.locator('.csv-import-section').last).to_be_visible()
                assert page.evaluate("""() => {
                    const csvPanel = document.querySelector('#csv-file').closest('.panel');
                    const layoutPanel = document.querySelector('#layout-canvas').closest('.panel');
                    return Boolean(csvPanel.compareDocumentPosition(layoutPanel) & Node.DOCUMENT_POSITION_FOLLOWING)
                        && layoutPanel.nextElementSibling.classList.contains('field-theme-settings');
                }""")
                expect(page.locator('#text-settings')).to_be_visible()
                expect(page.locator('#delete-box')).to_be_enabled()
                x_before=float(page.locator('#box-x').input_value())
                page.locator('#layout-canvas').focus()
                page.locator('#layout-canvas').press('ArrowRight')
                assert float(page.locator('#box-x').input_value()) == x_before + 1
                page.locator('.layout-box[data-key=binomial_name]').click(modifiers=['Shift'],position={'x':5,'y':5})
                expect(page.locator('#selection-count')).to_contain_text('2 boxes selected')
                page.locator('#box-w').fill('120')
                page.locator('#box-w').press('Tab')
                selected_widths=page.locator('.layout-box.selected').evaluate_all("els => els.map(el => parseFloat(el.style.width))")
                assert len(selected_widths)==2 and all(abs(width-66.6667)<0.01 for width in selected_widths)
                tops_before=page.locator('.layout-box.selected').evaluate_all("els => els.map(el => parseFloat(el.style.top))")
                page.locator('#layout-canvas').focus()
                page.locator('#layout-canvas').press('ArrowDown')
                tops_after=page.locator('.layout-box.selected').evaluate_all("els => els.map(el => parseFloat(el.style.top))")
                assert all(after > before for before,after in zip(tops_before,tops_after))
                page.locator('#selected-box').select_option('common_name')
                page.get_by_role('button',name='Center text',exact=True).click()
                page.get_by_role('button',name='Align text to bottom',exact=True).click()
                expect(page.get_by_role('button',name='Center text',exact=True)).to_have_attribute('aria-pressed','true')
                expect(page.get_by_role('button',name='Align text to bottom',exact=True)).to_have_attribute('aria-pressed','true')
                page.locator('#field-label').fill('Card name')
                page.locator('#field-label').press('Tab')
                expect(page.locator('#selected-box option:checked')).to_have_text('Card name')
                page.locator('#field-example').fill('Example organism')
                page.locator('#field-example').press('Tab')
                page.get_by_text('Add a content box',exact=True).click()
                page.locator('#new-key').fill('temporary_field')
                page.locator('#add-box').click()
                expect(page.locator('#selected-box')).to_have_value('temporary_field')
                page.once('dialog',lambda dialog:dialog.accept())
                page.locator('#delete-box').click()
                expect(page.locator('#selected-box option[value=temporary_field]')).to_have_count(0)
                page.locator('#save-layout').click()
                expect(page.locator('#layout-state')).to_contain_text('Saved')
                page.locator('#csv-file').set_input_files({'name':'cards.csv','mimeType':'text/csv','buffer':b'common_name,card_id,copies\nTest organism,test-organism,1\n'})
                expect(page.locator('#sample-row option')).to_have_count(1)
                page.locator('#import-student-name').fill('Ms. Rivera')
                page.locator('#import-class-name').fill('Period 7')
                page.locator('#validate-import').click()
                expect(page.locator('#import-summary')).to_contain_text('1 rows ready')
                expect(page.locator('#import-summary')).to_contain_text('Student: Ms. Rivera · Class: Period 7')
                page.once('dialog',lambda dialog:dialog.accept())
                page.locator('#commit-import').click()
                expect(page.locator('#studio-status')).to_contain_text('1 created')
                page.locator('[data-tab=overview]').click()
                expect(page.get_by_role('button',name='Edit Student for Test organism')).to_have_text('Ms. Rivera')
                expect(page.get_by_role('button',name='Edit Class for Test organism')).to_have_text('Period 7')
                page.get_by_role('button',name='Edit Student for Test organism').click()
                expect(page.locator('#student_name')).to_be_focused()
                expect(page.locator('#student_name')).to_have_value('Ms. Rivera')
                expect(page.locator('#class_name')).to_have_value('Period 7')
                page.locator('#student_name').fill('Teacher import')
                page.locator('#save-edits').click()
                expect(page.locator('#teacher-message')).to_have_text('Teacher edits saved.')
                expect(page.get_by_role('button',name='Edit Class for Test organism')).to_have_text('Period 7')
                page.get_by_role('button',name='Edit Class for Test organism').click()
                expect(page.locator('#class_name')).to_be_focused()
                page.locator('#close-review').click()
                page.locator('[data-tab=print]').click()
                expect(page.locator('#tab-print')).to_be_visible()
                page.locator('#include-imported').check()
                expect(page.locator('#print-cards tr')).to_have_count(1)
                page.locator('#select-visible').click()
                page.locator('#check-print').click()
                expect(page.locator('#print-status')).to_contain_text('Ready to download')
                with page.expect_popup() as popup:
                    page.locator('#preview-print').click()
                expect(page.locator('#print-status')).to_contain_text('Sheet preview opened')
                popup.value.close()
                with page.expect_download() as download:
                    page.locator('#download-print').click()
                assert download.value.suggested_filename.endswith('.pdf')
                page.locator('[data-tab=layout]').click()
                expect(page.locator('#download-svg')).to_be_visible()
                design=page.request.get(origin+page.locator('#download-svg').get_attribute('href')).body()
                page.locator('#svg-file').set_input_files({'name':'design.svg','mimeType':'image/svg+xml','buffer':design})
                expect(page.locator('#studio-status')).to_contain_text('SVG design loaded')
                page.goto(origin+'/teacher')
                row=page.locator('.project-row').filter(has_text='SVG browser test')
                page.once('dialog',lambda dialog:dialog.accept('Renamed browser test'))
                row.get_by_role('button',name='Rename').click()
                expect(page.locator('.project-row').filter(has_text='Renamed browser test')).to_be_visible()
                row=page.locator('.project-row').filter(has_text='Renamed browser test')
                page.once('dialog',lambda dialog:dialog.accept())
                row.get_by_role('button',name='Delete').click()
                expect(page.locator('.project-row').filter(has_text='Renamed browser test')).to_have_count(0)
                assert not errors,errors
                assert not external,external
                browser.close()
                print('Project browser smoke passed')
        finally:
            server.terminate();server.wait(timeout=5)
